// Shared Tailwind config for all FWI pages — load before Tailwind CDN
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#36003e",
        "on-primary-container": "#008abb",
        "tertiary-container": "#2f0037",
        "on-primary-fixed": "#001e2c",
        "secondary-fixed": "#6bff8f",
        "on-primary": "#00354a",
        "on-secondary-fixed": "#002109",
        "surface-tint": "#7bd0ff",
        "on-tertiary-container": "#ce3ae5",
        "on-surface": "#dae2fd",
        "inverse-primary": "#00668a",
        "secondary-fixed-dim": "#4ae176",
        "error": "#ffb4ab",
        "surface-bright": "#31394d",
        "on-error-container": "#ffdad6",
        "surface": "#0b1326",
        "on-background": "#dae2fd",
        "primary-fixed-dim": "#7bd0ff",
        "primary-fixed": "#c4e7ff",
        "inverse-on-surface": "#283044",
        "outline-variant": "#45464d",
        "on-secondary-container": "#004119",
        "on-tertiary-fixed-variant": "#7c008e",
        "tertiary-fixed": "#ffd6fd",
        "primary-container": "#001a27",
        "on-secondary-fixed-variant": "#005321",
        "on-secondary": "#003915",
        "on-surface-variant": "#c6c6cd",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#fbabff",
        "outline": "#909097",
        "surface-container-high": "#222a3d",
        "secondary-container": "#00b954",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-dim": "#0b1326",
        "secondary": "#4ae176",
        "background": "#0b1326",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004c69",
        "primary": "#7bd0ff",
        "inverse-surface": "#dae2fd",
        "on-tertiary": "#580065",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "tertiary": "#fbabff",
        "surface-container": "#171f33"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
};
